name: CI/CD
on:
  workflow_dispatch:
  #[push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run Script
        run: echo "Testing Action Display"
      - name: Run Multi-line Script
        run: |
          echo Adding other actions,
          echo Testing different steps.
