name: CodeVitals Check

on:
  workflow_dispatch:
  #push:
  #  branches: [main]
  # pull_request:
  #  branches: [main]

jobs:
  code-vitals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm install code-vitals --save-dev
      - run: npx code-v deps
      - run: npx code-v code
